In [78]:
import pandas as pd



In [79]:

df = pd.read_csv("Fraud.csv")

In [80]:
df

step      type      amount     nameOrig  oldbalanceOrg  \
0           1   PAYMENT     9839.64  C1231006815      170136.00   
1           1   PAYMENT     1864.28  C1666544295       21249.00   
2           1  TRANSFER      181.00  C1305486145         181.00   
3           1  CASH_OUT      181.00   C840083671         181.00   
4           1   PAYMENT    11668.14  C2048537720       41554.00   
...       ...       ...         ...          ...            ...   
6362615   743  CASH_OUT   339682.13   C786484425      339682.13   
6362616   743  TRANSFER  6311409.28  C1529008245     6311409.28   
6362617   743  CASH_OUT  6311409.28  C1162922333     6311409.28   
6362618   743  TRANSFER   850002.52  C1685995037      850002.52   
6362619   743  CASH_OUT   850002.52  C1280323807      850002.52   

         newbalanceOrig     nameDest  oldbalanceDest  newbalanceDest  isFraud  \
0             160296.36  M1979787155            0.00            0.00        0   
1              19384.72  M2044282225            0.00            0.00        0   
2                  0.00   C553264065            0.00            0.00        1   
3                  0.00    C38997010        21182.00            0.00        1   
4              29885.86  M1230701703            0.00            0.00        0   
...                 ...          ...             ...             ...      ...   
6362615            0.00   C776919290            0.00       339682.13        1   
6362616            0.00  C1881841831            0.00            0.00        1   
6362617            0.00  C1365125890        68488.84      6379898.11        1   
6362618            0.00  C2080388513            0.00            0.00        1   
6362619            0.00   C873221189      6510099.11      7360101.63        1   

         isFlaggedFraud  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
6362615               0  
6362616               0  
6362617               0  
6362618               0  
6362619               0  

[6362620 rows x 11 columns]

In [81]:
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB
None
               step        amount  oldbalanceOrg  newbalanceOrig  \
count  6.362620e+06  6.362620e+06   6.362620e+06    6.362620e+06   
mean   2.433972e+02  1.798619e+05   8.338831e+05    8.551137e+05   
std    1.423320e+02  6.038582e+05   2.888243e+06    2.924049e+06   
min    1.000000e+00  0.000000e+00   0.000000e+00    0.000000e+00   
25%    1.560000e+02  1.338957e+04   0.000000e+00    0.000000e+00   
50%    2.390000e+02  7.487194e+04

In [82]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [83]:
columns_to_drop = ['nameOrig', 'nameDest']


df=df.drop(columns=columns_to_drop,axis=1)

In [84]:
df['isFraud'].unique()

array([0, 1], dtype=int64)

In [85]:
df

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0           1   PAYMENT     9839.64      170136.00       160296.36   
1           1   PAYMENT     1864.28       21249.00        19384.72   
2           1  TRANSFER      181.00         181.00            0.00   
3           1  CASH_OUT      181.00         181.00            0.00   
4           1   PAYMENT    11668.14       41554.00        29885.86   
...       ...       ...         ...            ...             ...   
6362615   743  CASH_OUT   339682.13      339682.13            0.00   
6362616   743  TRANSFER  6311409.28     6311409.28            0.00   
6362617   743  CASH_OUT  6311409.28     6311409.28            0.00   
6362618   743  TRANSFER   850002.52      850002.52            0.00   
6362619   743  CASH_OUT   850002.52      850002.52            0.00   

         oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                  0.00            0.00        0               0  
1                  0.00            0.00        0               0  
2                  0.00            0.00        1               0  
3              21182.00            0.00        1               0  
4                  0.00            0.00        0               0  
...                 ...             ...      ...             ...  
6362615            0.00       339682.13        1               0  
6362616            0.00            0.00        1               0  
6362617        68488.84      6379898.11        1               0  
6362618            0.00            0.00        1               0  
6362619      6510099.11      7360101.63        1               0  

[6362620 rows x 9 columns]

In [86]:
from sklearn.preprocessing import LabelEncoder

In [87]:
column_name = 'type'
label_encoder = LabelEncoder()
df[column_name + '_encoded'] = label_encoder.fit_transform(df[column_name])
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Label Mapping:", label_mapping)



Label Mapping: {'CASH_IN': 0, 'CASH_OUT': 1, 'DEBIT': 2, 'PAYMENT': 3, 'TRANSFER': 4}


In [88]:
df

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0           1   PAYMENT     9839.64      170136.00       160296.36   
1           1   PAYMENT     1864.28       21249.00        19384.72   
2           1  TRANSFER      181.00         181.00            0.00   
3           1  CASH_OUT      181.00         181.00            0.00   
4           1   PAYMENT    11668.14       41554.00        29885.86   
...       ...       ...         ...            ...             ...   
6362615   743  CASH_OUT   339682.13      339682.13            0.00   
6362616   743  TRANSFER  6311409.28     6311409.28            0.00   
6362617   743  CASH_OUT  6311409.28     6311409.28            0.00   
6362618   743  TRANSFER   850002.52      850002.52            0.00   
6362619   743  CASH_OUT   850002.52      850002.52            0.00   

         oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  type_encoded  
0                  0.00            0.00        0               0             3  
1                  0.00            0.00        0               0             3  
2                  0.00            0.00        1               0             4  
3              21182.00            0.00        1               0             1  
4                  0.00            0.00        0               0             3  
...                 ...             ...      ...             ...           ...  
6362615            0.00       339682.13        1               0             1  
6362616            0.00            0.00        1               0             4  
6362617        68488.84      6379898.11        1               0             1  
6362618            0.00            0.00        1               0             4  
6362619      6510099.11      7360101.63        1               0             1  

[6362620 rows x 10 columns]

In [89]:
df=df.drop(columns='type',axis=1)

In [90]:
import numpy as np

In [158]:
from scipy import stats


column_name = 'amount'  


z_scores = stats.zscore(df[column_name])


z_threshold = 0.0999

outliers_mask = (abs(z_scores) > z_threshold)

df = df[~outliers_mask]

In [159]:
df


step     amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
15          1  229133.94       15325.00            0.00         5083.00   
19          1  215310.30         705.00            0.00        22425.00   
71          1  136872.92      162075.98        25203.05       217806.00   
82          1  224606.64           0.00            0.00       354678.92   
83          1  125872.53           0.00            0.00       348512.00   
...       ...        ...            ...             ...             ...   
6362565   739  156691.56      156691.56            0.00       842252.15   
6362568   739  194521.28      194521.28            0.00            0.00   
6362569   739  194521.28      194521.28            0.00      7203373.74   
6362594   741  144945.34      144945.34            0.00            0.00   
6362595   741  144945.34      144945.34            0.00            0.00   

         newbalanceDest  isFraud  isFlaggedFraud  type_encoded  
15             51513.44        0               0             1  
19                 0.00        0               0             4  
71                 0.00        0               0             1  
82                 0.00        0               0             4  
83           3420103.09        0               0             4  
...                 ...      ...             ...           ...  
6362565       998943.71        1               0             1  
6362568            0.00        1               0             4  
6362569      7397895.02        1               0             1  
6362594            0.00        1               0             4  
6362595       144945.34        1               0             1  

[1261386 rows x 9 columns]

In [160]:
df.sort_values(by='isFraud')

step     amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
15          1  229133.94       15325.00            0.00         5083.00   
4223434   306  225057.92       10216.00            0.00        77847.01   
4223433   306  220506.91       10073.00       230579.91        38073.48   
4223429   306  186474.39       11654.00            0.00      5563633.14   
4223426   306  129878.51       50462.00            0.00       282935.93   
...       ...        ...            ...             ...             ...   
2382177   200  159232.01      159232.01            0.00            0.00   
2382161   198  152961.49      152961.49            0.00     12414395.47   
2382160   198  152961.49      152961.49            0.00            0.00   
6039444   481  130668.56      130668.56            0.00      2403740.71   
6362595   741  144945.34      144945.34            0.00            0.00   

         newbalanceDest  isFraud  isFlaggedFraud  type_encoded  
15             51513.44        0               0             1  
4223434       302904.93        0               0             1  
4223433            0.00        0               0             0  
4223429      5750107.53        0               0             1  
4223426       412814.44        0               0             1  
...                 ...      ...             ...           ...  
2382177       159232.01        1               0             1  
2382161     12567356.96        1               0             1  
2382160            0.00        1               0             4  
6039444      2534409.27        1               0             1  
6362595       144945.34        1               0             1  

[1261386 rows x 9 columns]

In [161]:
df['isFraud'].unique()

array([0, 1], dtype=int64)

In [162]:
columns_to_drops = ['isFraud','isFlaggedFraud']


X=df.drop(columns=columns_to_drops,axis=1)
y = df['isFraud']

In [163]:
X

step     amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
15          1  229133.94       15325.00            0.00         5083.00   
19          1  215310.30         705.00            0.00        22425.00   
71          1  136872.92      162075.98        25203.05       217806.00   
82          1  224606.64           0.00            0.00       354678.92   
83          1  125872.53           0.00            0.00       348512.00   
...       ...        ...            ...             ...             ...   
6362565   739  156691.56      156691.56            0.00       842252.15   
6362568   739  194521.28      194521.28            0.00            0.00   
6362569   739  194521.28      194521.28            0.00      7203373.74   
6362594   741  144945.34      144945.34            0.00            0.00   
6362595   741  144945.34      144945.34            0.00            0.00   

         newbalanceDest  type_encoded  
15             51513.44             1  
19                 0.00             4  
71                 0.00             1  
82                 0.00             4  
83           3420103.09             4  
...                 ...           ...  
6362565       998943.71             1  
6362568            0.00             4  
6362569      7397895.02             1  
6362594            0.00             4  
6362595       144945.34             1  

[1261386 rows x 7 columns]

In [164]:
y

15         0
19         0
71         0
82         0
83         0
          ..
6362565    1
6362568    1
6362569    1
6362594    1
6362595    1
Name: isFraud, Length: 1261386, dtype: int64

In [165]:
y.unique()

array([0, 1], dtype=int64)

In [166]:

from sklearn.model_selection import train_test_split

In [167]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [168]:
from sklearn.ensemble import RandomForestClassifier

In [169]:
model = RandomForestClassifier(random_state=42)

In [170]:

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [202]:
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score

In [203]:
y_pred = model.predict(X_test)

In [205]:
X.columns

Index(['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest',
       'newbalanceDest', 'type_encoded'],
      dtype='object')

In [206]:
unseen_data = pd.DataFrame({
    'step':[741],
    
    'amount':[144945.34],
    'oldbalanceOrg':[144945.34],
     'newbalanceOrig':[0.00],
     'oldbalanceDest':[0.00],
     'newbalanceDest':[144945.34],
     'type_encoded':[1]
},index=[0])

In [207]:
model.predict(unseen_data)

array([1], dtype=int64)

About the Model:
         
The dataset, simulating a 30-day financial scenario, guides the development of a fraud detection model using Random forest. Key variables like transaction type, amount, and balance-related columns are pivotal. Employing Z-Score outlier removal and feature engineering, the model identifies potential fraud patterns. Categorical variables undergo label encoding, and the dataset is split for training and testing.

Selection of variables:


The variables selected for your fraud detection model exhibit a thoughtful consideration of temporal, transactional, and balance-related aspects. 'Step' captures the temporal dimension, allowing the model to discern patterns over the simulation period. 'Amount' reflects the transaction value, a pivotal indicator for fraud detection. Balances—both initial and new—of originator and recipient accounts ('oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest') contribute to identifying anomalies. Lastly, the encoded transaction type ('type_encoded') encapsulates diverse transaction categories, aiding the model in distinguishing fraudulent patterns. This selection forms a comprehensive set of features, reflecting a holistic approach to capturing potential fraud indicators in the financial simulation data.

Performance of the model

In [208]:
print(accuracy_score(y_test, y_pred))

print(precision_score(y_test, y_pred))

print(recall_score(y_test, y_pred))

print(f1_score(y_test, y_pred))

0.999599648007357
0.900709219858156
0.5934579439252337
0.7154929577464789


Key factors that predict fraudulent customer:


Predicting fraudulent customers involves scrutinizing unusual transaction patterns, atypical amounts, and irregular transaction times. Factors like unexpected balance changes, geographical inconsistencies, and high velocity transactions play a crucial role. 


Yes, these factors make sense for predicting fraudulent customer behavior. Unusual transaction patterns, abnormal amounts, atypical transaction times, and other indicators are logical markers of fraudulent activity. Machine learning models can effectively leverage these features to discern anomalies and enhance the accuracy of fraud detection, ensuring the security of financial 

Preventions adopted by the company while updating its infrastructure:



1.Perform regular data backups to prevent loss during the infrastructure update.
2.Conduct thorough security audits to identify and address vulnerabilities.
3.Provide cybersecurity training to employees for increased awareness.
4.Keep all software and systems updated with the latest security patches.
5.Review and update access controls to limit access to authorized personnel.
6.Develop and update an incident response plan to handle security incidents.
7.Establish a testing environment for thorough testing before deployment.
8.Implement encryption for in-transit and at-rest data protection.
9.Conduct security assessments for third-party vendors.
10.Implement robust monitoring and logging mechanisms for prompt incident detection and response.



After implementing the actions this is how it works:


1.Regularly monitor systems, logs, and alerts for unusual activities to detect potential security incidents.
2.Conduct periodic incident response tests and penetration testing to validate the effectiveness of response mechanisms and identify vulnerabilities.
3.Schedule security audits and assessments to evaluate overall security measures, both internally and externally.
4.Review user access controls, conduct compliance checks, and test data backups to ensure security compliance and data recovery capabilities.
5.Encourage user feedback, conduct incident reviews, and define key performance indicators (KPIs) to continuously assess and improve security measures.
